/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fenetre;
import javax.swing.JOptionPane;
/**
 *
 * @author boursaliamel
 */
public class Candidats extends javax.swing.JFrame {
//projet L2 MIASHS Amel BOUABDELLAH BOURSALI 400000259 et Ayoub KHAYEF ALLAH 40000476
    /**
     * Creates new form Candidats
     */
    public Candidats() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Precedent = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        asli = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        nirai = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ayoub = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        Florine = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        mouna = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        ines = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        fadoua = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        ahmed = new javax.swing.JButton();
        Deconnexion = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        amel = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        ndou = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/logoufr-SEGMI.jpeg"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(270, 76));
        jLabel2.setMinimumSize(new java.awt.Dimension(270, 76));
        jLabel2.setMixingCutoutShape(null);

        Precedent.setText("<");
        Precedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecedentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1070, Short.MAX_VALUE)
                .addComponent(Precedent, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Precedent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(232, 240, 248));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_1999.jpg"))); // NOI18N
        jLabel3.setText("PHOTO");

        jLabel4.setText("TAS");

        jLabel5.setText("Asli");

        jLabel6.setText("L2 Economie Gestion");

        jLabel1.setText("19 ans");

        asli.setBackground(new java.awt.Color(255, 255, 255));
        asli.setText("Programme");
        asli.setFocusable(false);
        asli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(asli))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(asli)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(232, 240, 248));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_1997.jpg"))); // NOI18N

        jLabel9.setText("RAVIMOHAN");

        jLabel10.setText("NIRAIKSAN");

        jLabel11.setText("L2 DL Informatique Gestion");

        jLabel12.setText("20 ans");

        nirai.setBackground(new java.awt.Color(255, 255, 255));
        nirai.setText("Programme");
        nirai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niraiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(nirai)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(nirai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(232, 240, 248));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/PHOTO-2022-03-05-15-07-59.jpg"))); // NOI18N

        jLabel15.setText("KHAYEF-ALLAH");

        jLabel16.setText("Ayoub");

        jLabel17.setText("L2 DL Informatique Gestion");

        jLabel18.setText("21 ans");

        ayoub.setBackground(new java.awt.Color(255, 255, 255));
        ayoub.setText("Programme");
        ayoub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayoubActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ayoub)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(ayoub)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(232, 240, 248));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_1998.jpg"))); // NOI18N
        jLabel20.setText("PHOTO");

        jLabel21.setText("PHILLIPE");

        jLabel22.setText("Florine");

        jLabel23.setText("L2 DL Informatique Gestion");

        jLabel24.setText("20 ans");

        Florine.setBackground(new java.awt.Color(255, 255, 255));
        Florine.setText("Programme");
        Florine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlorineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel21)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(Florine)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel20)
                .addGap(30, 30, 30)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(12, 12, 12)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(Florine)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(232, 240, 248));

        jLabel33.setText("AHMIM");

        jLabel34.setText("Mouna");

        jLabel35.setText("L2 Economie gestion");

        jLabel36.setText("20 ans");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2001.JPG"))); // NOI18N
        jLabel27.setText("PHOTO");

        mouna.setBackground(new java.awt.Color(255, 255, 255));
        mouna.setText("Programme");
        mouna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mounaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel33)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(mouna))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel27)
                .addGap(30, 30, 30)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addGap(18, 18, 18)
                .addComponent(mouna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(232, 240, 248));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2002.jpg"))); // NOI18N

        jLabel63.setText("TOHNOGO");

        jLabel64.setText("Ines");

        jLabel65.setText("L2 Droit");

        jLabel66.setText("19 ans");

        ines.setBackground(new java.awt.Color(255, 255, 255));
        ines.setText("Programme");
        ines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel64)
                            .addComponent(jLabel63)
                            .addComponent(jLabel66)
                            .addComponent(jLabel65)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel62))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(ines)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel63)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel64)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel65)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel66)
                .addGap(18, 18, 18)
                .addComponent(ines)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(232, 240, 248));

        jLabel69.setText("KASMI");

        jLabel70.setText("Fadoua");

        jLabel71.setText("L2 STAPS");

        jLabel72.setText("22 ans");

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2022.JPG"))); // NOI18N

        fadoua.setBackground(new java.awt.Color(255, 255, 255));
        fadoua.setText("Programme");
        fadoua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fadouaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fadoua)
                    .addComponent(jLabel70)
                    .addComponent(jLabel69)
                    .addComponent(jLabel71)
                    .addComponent(jLabel72))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel69)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel70)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel71)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel72)
                .addGap(18, 18, 18)
                .addComponent(fadoua)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        jPanel16.setBackground(new java.awt.Color(232, 240, 248));

        jLabel75.setText("EL TEWIL");

        jLabel76.setText("Ahmed");

        jLabel77.setText("L2 MIASHS");

        jLabel78.setText("19 ans");

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_0506 2.JPG"))); // NOI18N

        ahmed.setBackground(new java.awt.Color(255, 255, 255));
        ahmed.setText("Programme");
        ahmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahmedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ahmed)
                    .addComponent(jLabel76)
                    .addComponent(jLabel75)
                    .addComponent(jLabel78)
                    .addComponent(jLabel77)
                    .addComponent(jLabel80))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel75)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel78)
                .addGap(18, 18, 18)
                .addComponent(ahmed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Deconnexion.setBackground(new java.awt.Color(255, 255, 255));
        Deconnexion.setText("DECONNEXION");
        Deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionActionPerformed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(232, 240, 248));

        jLabel73.setText("BOURSALI");

        jLabel74.setText("Amel");

        jLabel79.setText("L2 MIASHS");

        jLabel82.setText("19 ans");

        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2012.PNG"))); // NOI18N

        amel.setBackground(new java.awt.Color(255, 255, 255));
        amel.setText("Programme");
        amel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amel)
                    .addComponent(jLabel83)
                    .addComponent(jLabel74)
                    .addComponent(jLabel73)
                    .addComponent(jLabel79)
                    .addComponent(jLabel82))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel73)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel74)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel79)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel82)
                .addGap(18, 18, 18)
                .addComponent(amel)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(232, 240, 248));

        jLabel84.setText("BAYO");

        jLabel85.setText("Ndoumbé");

        jLabel86.setText("L2 Psychologie");

        jLabel87.setText("19 ans");

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2023.JPG"))); // NOI18N

        ndou.setBackground(new java.awt.Color(255, 255, 255));
        ndou.setText("Programme");
        ndou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndouActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ndou)
                    .addComponent(jLabel85)
                    .addComponent(jLabel84)
                    .addComponent(jLabel86)
                    .addComponent(jLabel87))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel88)
                .addGap(46, 46, 46))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel88)
                .addGap(30, 30, 30)
                .addComponent(jLabel84)
                .addGap(18, 18, 18)
                .addComponent(jLabel85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel86)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ndou)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Deconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Deconnexion)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//permet à l'utilisateur de revenir à la page prcécédente
    private void PrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecedentActionPerformed
        new Connexion().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_PrecedentActionPerformed
//permet à l'utilisateur de se deconnecter
    private void DeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionActionPerformed
        // TODO add your handling code here:
        new Electio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DeconnexionActionPerformed
//affichage du programe pour asli tas 
    private void asliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asliActionPerformed
    JOptionPane.showMessageDialog(null,"Membre de l’association étudiante LA FAX\n" +
"> Renforcer le bien-être de nos étudiants : \n" +
"Lutter contre toutes les formes de violences sexistes et sexuelles et violences associées au sein de notre université et faire connaître la cellule d’écoute et d’accompagnement des victimes de violences sexistes et sexuelles.\n" +
"Former l’ensemble des associations étudiantes, les personnel/les administratif/es et enseignant/e/s chercheurs/euses à la lutte contre les violences sexistes et sexuelles et la prise en charge des victimes.\n" +
"Développer un dispositif de personne de confiance au sein des soirées étudiantes.\n" +
"Diversifier et développer les services de santé universitaire pour répondre aux demandes des étudiant/e/s et accueillir l’ensemble des étudiant/e/s qui en font la demande (reprise des consultations gynéco, embauche de psys...).\n" +
"\n" +
"> Pour des formations accessibles à toutes et à tous :\n" +
"Lutter pour une université gratuite et à moindre coût pour les étudiant/e/s français et internationaux/ales.\n" +
"Développer la valorisation de l’engagement étudiant en promouvant notamment le régime spécifique d’étude et en valorisant l’année de césure.\n" +
"Développer des méthodes d'apprentissage plus interactives, attractives, innovantes et professionnalisantes pour l’ensemble des étudiant/e/s.\n" +
"Généraliser l’approche par compétences pour favoriser la personnalisation du parcours de formation.\n" +
"Créer des UE transversales pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"\n" +
"> Vie étudiante : \n" +
"Créer un guichet d’accès aux droits pour accompagner les étudiant.es dans leurs démarches.\n" +
"Rendre plus accessible la pratique sportive aux étudiant.es en élargissant les plages horaires du SUAPS et en diversifiant les activités proposées.\n" +
"Rendre toujours plus transparente la CVEC et augmenter le financement des projets étudiants.\n" +
"Traduire le site internet de l’université dans différentes langues et le rendre inclusif pour tous/tes.\n" +
"Développer l’accompagnement à la recherche de jobs étudiants.\n" +
"Élargir les horaires d’ouverture de la BU.\n" ,          
            "Programme Asli Tas", JOptionPane.PLAIN_MESSAGE);
 
    }//GEN-LAST:event_asliActionPerformed
//affichage du programe pour niraiksan ravimohan
    private void niraiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niraiActionPerformed
       JOptionPane.showMessageDialog(null,"Membre de l’association étudiante LA BOURSE POUR TOUT LE MONDE\n" +
"> Le bien-être étudiant est notre priorité  : \n" +
"Les racistes et réactionnaires ont le vent en poupe, leurs candidats passent tous les jours à la télé. Cela a encouragé des groupes d’extrême-droite de tenter de s’implanter à la fac.\n" +
"La Cocarde a d’abord tenté, mais après avoir été, à de nombreuses reprises, repoussée en dehors de la fac, ils ont finalement abandonné : ils ne se sont même pas présentés à ces élections ! \n " +
"Par contre, nous avons l’UNI... qui se revendique de défendre la “liberté d’étudier”, la réussite, mais dont les principaux dirigeants appellent à voter pour Eric Zemmour, \n "+
"un raciste notoire qui défend la déportation des musulmans ainsi qu’un discours profondément misogyne. Voter UNEF à ces élections, le syndicat qui combat ces idées, \n "+
"c’est la meilleure façon de rejeter leurs idées nauséabondes. C’est aussi soutenir un syndicat qui a obtenu la régularisation de nombreux étudiant/e/s étranger/e/s, \n" +
"l’annulation d’expulsions et qui milite pour l’égalité des droits entre tous les étudiant/e/s.\n" +
"\n" +
"> Une formation pour tout le monde \n" +
"Créer des UE transversales pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"Augmenter les capacités d’accueil en master pour permettre à toutes et tous de bénéficier du droit à la poursuite d’études.\n" +
"Améliorer les conditions de recherche pour les doctorant/e/s : prise en charge des frais complémentaires, veille à la bonne application de la mensualisation des heures de vacations pour les chargé/e/s de TD.\n" +
"Exonérer automatiquement d’au moins 50% les frais d’inscription des doctorant.es (jusqu’à 100% sur critères sociaux).\n" +
"\n" +
"> Vie étudiante : \n" +
"Améliorer la communication de l'université et rendre plus accessible son site internet.\n" +
"Rendre plus accessible la pratique sportive aux étudiant.es en élargissant les plages horaires du SUAPS et en diversifiant les activités proposées.\n" +
"Rendre toujours plus transparente la CVEC et augmenter le financement des projets étudiants.\n" +
"Développer une application pour la vie étudiante et de campus.\n" +
"Développer les parkings à vélo sécurisés sur les campus pour tendre vers des mobilités plus douces pour se déplacer à l’université.\n" +
"Développer le tri sélectif à l’université et la valorisation des déchets organiques.\n",
               "Programme Niraiksan Ravimohan",  JOptionPane.PLAIN_MESSAGE);
    
    }//GEN-LAST:event_niraiActionPerformed
//affichage du programe pour ayoub khayef allah 
    private void ayoubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayoubActionPerformed
       JOptionPane.showMessageDialog(null,"Membre de l’association étudiante ONETWOTHREEVIVADZ\n" +
"> La vie étudiante : \n" +
"Lutter contre toutes les formes de violences sexistes et sexuelles et violences associées au sein de notre université et faire connaître la cellule d’écoute et d’accompagnement des victimes de violences sexistes et sexuelles.\n" +
"Former l’ensemble des associations étudiantes, les personnel/les administratif/es et enseignant/e/s chercheurs/euses à la lutte contre les violences sexistes et sexuelles et la prise en charge des victimes.\n" +
"Développer un dispositif de personne de confiance au sein des soirées étudiantes.\n" +
"Diversifier et développer les services de santé universitaire pour répondre aux demandes des étudiant/e/s et accueillir l’ensemble des étudiant/e/s qui en font la demande (reprise des consultations gynéco, embauche de psys...).\n" +
"\n" +
"> Pour des formations accessibles à toutes et à tous :\n" +
"Lutter pour une université gratuite et à moindre coût pour les étudiant/e/s français et internationaux/ales.\n" +
"Développer la valorisation de l’engagement étudiant en promouvant notamment le régime spécifique d’étude et en valorisant l’année de césure.\n" +
"Développer des méthodes d'apprentissage plus interactives, attractives, innovantes et professionnalisantes pour l’ensemble des étudiant/e/s.\n" +
"Généraliser l’approche par compétences pour favoriser la personnalisation du parcours de formation.\n" +
"Créer des UE transversales pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"\n" +
"> Nos nouveautés : \n" +
"Créer un guichet d’accès aux droits pour accompagner les étudiant.es dans leurs démarches.\n" +
"Rendre plus accessible la pratique sportive aux étudiant.es en élargissant les plages horaires du SUAPS et en diversifiant les activités proposées.\n" +
"Rendre toujours plus transparente la CVEC et augmenter le financement des projets étudiants.\n" +
"Traduire le site internet de l’université dans différentes langues et le rendre inclusif pour tous/tes.\n" +
"Développer l’accompagnement à la recherche de jobs étudiants.\n" +
"Élargir les horaires d’ouverture de la BU.\n" ,         
            "Programme Ayoub Khayef-Allah", JOptionPane.PLAIN_MESSAGE); 
       
      
    }//GEN-LAST:event_ayoubActionPerformed
//affichage du programe pour florine phillipe
    private void FlorineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlorineActionPerformed
         JOptionPane.showMessageDialog(null,"Membre de l’association étudiante ZIZIR\n" +
"> Côté bien-être : \n" +
"Renforcer les dispositifs d’aides et d’accompagnement psychologique au sein de notre université, et communiquer sur les dispositifs gratuits existants.\n" +
"Développer les dispositifs d’aides sociales et de lutte contre la précarité en les rendant plus lisibles et accessibles.\n" +
"Recrutement d’un/e assistant/e social/e, salarié/e de l’université, pour accélérer le traitement des dossiers.\n" +
"\n" +
"> Côté scolarité !\n" +
"Depuis septembre 2020 les UE fondamentales, celles avec les plus lourds coefficients, ne se compensent plus avec le reste des matières.\n " +
"Pour valider son année, l’étudiant/e doit avoir 10 de moyenne générale et plus de 10 à ses matières fondamentales alors que cela n'était pas le cas avant. \n" + 
"Ainsi pour compenser ce changement dévarobale pour la majorité des étudiants nous voudrons créer des UE transversales. \n" + 
"pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"Augmenter les capacités d’accueil en master pour permettre à toutes et tous de bénéficier du droit à la poursuite d’études.\n" +
"Améliorer les conditions de recherche pour les doctorant/e/s : prise en charge des frais complémentaires ...\n" +
"Exonérer automatiquement d’au moins 50% les frais d’inscription des doctorant.es (jusqu’à 100% sur critères sociaux). \n " +
"des étudiant/e/s et de l’UNEF a permis de regagner la 3e absence autorisée ainsi que la semaine de révision, des droits qui avaient été supprimés en 2020. \n" + 
"Il faut donc poursuivre !\n" +
"\n" +
"> Côté vie étudiante : \n" +
"Améliorer la communication de l'université et rendre plus accessible son site internet.\n" +
"Mettre en place des débats étudiants pour que l’université lutte activement contre le changement climatique.\n" +
"Développer une application pour la vie étudiante et de campus.\n" +
"Développer les parkings à vélo sécurisés sur les campus pour tendre vers des mobilités plus douces pour se déplacer à l’université.\n" +
"Développer le tri sélectif à l’université et la valorisation des déchets organiques.\n",
               "Programme Florine Philipe",  JOptionPane.PLAIN_MESSAGE);

    }//GEN-LAST:event_FlorineActionPerformed
//affichage du programe pour mouna ahmim
    private void mounaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mounaActionPerformed
       JOptionPane.showMessageDialog(null,"Membre de l’association étudiante UNEF\n" +
"> Renforcer le bien-être de nos étudiants : \n" +
"Renforcer les dispositifs d’aides et d’accompagnement psychologique au sein de notre université, et communiquer sur les dispositifs gratuits existants.\n" +
"Développer les dispositifs d’aides sociales et de lutte contre la précarité en les rendant plus lisibles et accessibles.\n" +
"Recrutement d’un/e assistant/e social/e, salarié/e de l’université, pour accélérer le traitement des dossiers.\n" +
"\n" +
"> Pour le retour de la compensation intégrale - non à la sélection au cours de nos études !\n" +
"Depuis septembre 2020 les UE fondamentales, celles avec les plus lourds coefficients, ne se compensent plus avec le reste des matières. \n" +
"Pour valider son année, l’étudiant/e doit avoir 10 de moyenne générale et plus de 10 à ses matières fondamentales. Or, avant, il suffisait \n"+ 
"uniquement d’avoir plus de 10 à sa moyenne générale pour valider son année. La suppression de ce droit ne sert qu’à renforcer la \n" +
"sélection au cours de nos études, c’est pour cela que nous exigeons le rétablissement de la compensation intégrale. La mobilisation \n" + 
"des étudiant/e/s et de l’UNEF a permis de regagner la 3e absence autorisée ainsi que la semaine de révision, des droits qui avaient été supprimés en 2020. \n" + 
 "Il faut donc poursuivre !\n" +
"\n" +
"> Vie étudiante : \n" +
"Améliorer la communication de l'université et rendre plus accessible son site internet.\n" +
"Mettre en place des débats étudiants pour que l’université lutte activement contre le changement climatique.\n" +
"Développer une application pour la vie étudiante et de campus.\n" +
"Développer les parkings à vélo sécurisés sur les campus pour tendre vers des mobilités plus douces pour se déplacer à l’université.\n" +
"Développer le tri sélectif à l’université et la valorisation des déchets organiques.\n",
               "Programme Mouna Ahmim",  JOptionPane.PLAIN_MESSAGE);
                                            
    }//GEN-LAST:event_mounaActionPerformed
//affichage du programe pour ines tohngodo
    private void inesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inesActionPerformed
        JOptionPane.showMessageDialog(null,"Membre de l’association étudiante IJEP\n" +
"> Lutter contre l'oppression de la Droite : \n" +
"Les racistes et réactionnaires ont le vent en poupe, leurs candidats passent tous les jours à la télé. Cela a encouragé des groupes d’extrême-droite de tenter de s’implanter à la fac.\n" +
"La Cocarde a d’abord tenté, mais après avoir été, à de nombreuses reprises, repoussée en dehors de la fac, ils ont finalement abandonné : ils ne se sont même pas présentés à ces élections ! \n " +
"Par contre, nous avons l’UNI... qui se revendique de défendre la “liberté d’étudier”, la réussite, mais dont les principaux dirigeants appellent à voter pour Eric Zemmour, \n "+
"un raciste notoire qui défend la déportation des musulmans ainsi qu’un discours profondément misogyne. Voter UNEF à ces élections, le syndicat qui combat ces idées, \n "+
"c’est la meilleure façon de rejeter leurs idées nauséabondes. C’est aussi soutenir un syndicat qui a obtenu la régularisation de nombreux étudiant/e/s étranger/e/s, \n" +
"l’annulation d’expulsions et qui milite pour l’égalité des droits entre tous les étudiant/e/s.\n" +
"\n" +
"> Une formation ouverte à tous\n" +
"Créer des UE transversales pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"Augmenter les capacités d’accueil en master pour permettre à toutes et tous de bénéficier du droit à la poursuite d’études.\n" +
"Améliorer les conditions de recherche pour les doctorant/e/s : prise en charge des frais complémentaires, veille à la bonne application de la mensualisation des heures de vacations pour les chargé/e/s de TD.\n" +
"Exonérer automatiquement d’au moins 50% les frais d’inscription des doctorant.es (jusqu’à 100% sur critères sociaux).\n" +
"\n" +
"> Vie étudiante : \n" +
"Améliorer la communication de l'université et rendre plus accessible son site internet.\n" +
"Rendre plus accessible la pratique sportive aux étudiant.es en élargissant les plages horaires du SUAPS et en diversifiant les activités proposées.\n" +
"Rendre toujours plus transparente la CVEC et augmenter le financement des projets étudiants.\n" +
"Développer une application pour la vie étudiante et de campus.\n" +
"Développer les parkings à vélo sécurisés sur les campus pour tendre vers des mobilités plus douces pour se déplacer à l’université.\n" +
"Développer le tri sélectif à l’université et la valorisation des déchets organiques.\n",
               "Programme Ines Tohngodo",  JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_inesActionPerformed
//affichage du programe pour ahmed el tewil 
    private void ahmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahmedActionPerformed

         JOptionPane.showMessageDialog(null,"Membre de l’association étudiante SMILE\n" +
"> Le bien-être de nos étudiants avant tout : \n" +
"Lutter contre toutes les formes de violences sexistes et sexuelles et violences associées au sein de notre université et faire connaître la cellule d’écoute et d’accompagnement des victimes de violences sexistes et sexuelles.\n" +
"Former l’ensemble des associations étudiantes, les personnel/les administratif/es et enseignant/e/s chercheurs/euses à la lutte contre les violences sexistes et sexuelles et la prise en charge des victimes.\n" +
"Développer un dispositif de personne de confiance au sein des soirées étudiantes.\n" +
"Diversifier et développer les services de santé universitaire pour répondre aux demandes des étudiant/e/s et accueillir l’ensemble des étudiant/e/s qui en font la demande (reprise des consultations gynéco, embauche de psys...).\n" +
"\n" +
"> Un accès libre à la formation :\n" +
"Lutter pour une université gratuite et à moindre coût pour les étudiant/e/s français et internationaux/ales.\n" +
"Développer la valorisation de l’engagement étudiant en promouvant notamment le régime spécifique d’étude et en valorisant l’année de césure.\n" +
"Développer des méthodes d'apprentissage plus interactives, attractives, innovantes et professionnalisantes pour l’ensemble des étudiant/e/s.\n" +
"Généraliser l’approche par compétences pour favoriser la personnalisation du parcours de formation.\n" +
"Créer des UE transversales pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"\n" +
"> Vie étudiante plus dynamique  : \n" +
"Créer un guichet d’accès aux droits pour accompagner les étudiant.es dans leurs démarches.\n" +
"Rendre plus accessible la pratique sportive aux étudiant.es en élargissant les plages horaires du SUAPS et en diversifiant les activités proposées.\n" +
"Rendre toujours plus transparente la CVEC et augmenter le financement des projets étudiants.\n" +
"Traduire le site internet de l’université dans différentes langues et le rendre inclusif pour tous/tes.\n" +
"Développer l’accompagnement à la recherche de jobs étudiants.\n"+
"Élargir les horaires d’ouverture de la BU.\n" ,         
            "Programme Ahmed El tewil ", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ahmedActionPerformed
//affichage du programe pour fadoua kasmi
    private void fadouaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fadouaActionPerformed
         JOptionPane.showMessageDialog(null,"Membre de l’association étudiante La FAMILLE\n" +
"> La vie étudiante : \n" +
"Lutter contre toutes les formes de violences sexistes et sexuelles et violences associées au sein de notre université et faire connaître la cellule d’écoute et d’accompagnement des victimes de violences sexistes et sexuelles.\n" +
"Développer un dispositif de personne de confiance au sein des soirées étudiantes.\n" +
"Diversifier et développer les services de santé universitaire pour répondre aux demandes des étudiant/e/s et accueillir l’ensemble des étudiant/e/s qui en font la demande (reprise des consultations gynéco, embauche de psys...).\n" +
"Permettre à tous les étudiants de pratiquer un sport au sein de l'université gratuitement.\n" +
"Renforcer les dispositifs d’aides et d’accompagnement psychologique au sein de notre université, et communiquer sur les dispositifs gratuits existants.\n"+
"Développer les dispositifs d’aides sociales et de lutte contre la précarité en les rendant plus lisibles et accessibles.\n" +
"> L'égalité pour TOUS :\n" +
"Lutter pour une université gratuite et à moindre coût pour les étudiant/e/s français et internationaux/ales.\n" +
"Développer la valorisation de l’engagement étudiant en promouvant notamment le régime spécifique d’étude et en valorisant l’année de césure.\n" +
"Développer des méthodes d'apprentissage plus interactives, attractives, innovantes et professionnalisantes pour l’ensemble des étudiant/e/s.\n" +
"Généraliser l’approche par compétences pour favoriser la personnalisation du parcours de formation.\n" +
"Créer des UE transversales pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"\n" +
"> Petit kiff en plus : \n" +
"Créer un guichet d’accès aux droits pour accompagner les étudiant.es dans leurs démarches.\n" +
"Rendre plus accessible la pratique sportive aux étudiant.es en élargissant les plages horaires du SUAPS et en diversifiant les activités proposées.\n" +
"Rendre toujours plus transparente la CVEC et augmenter le financement des projets étudiants.\n" +
"Traduire le site internet de l’université dans différentes langues et le rendre inclusif pour tous/tes.\n" +
"Développer l’accompagnement à la recherche de jobs étudiants.\n" +
"Élargir les horaires d’ouverture de la BU.\n" ,           
            "Programme Fadoua Kasmi", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_fadouaActionPerformed
//affichage du programe pour amel boursali
    private void amelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amelActionPerformed
         JOptionPane.showMessageDialog(null,"Membre de l’association étudiante OJO\n" +
"> Renforcer le bien-être de nos étudiants : \n" +
"Lutter contre toutes les formes de violences sexistes et sexuelles et violences associées au sein de notre université et faire connaître la cellule d’écoute et d’accompagnement des victimes de violences sexistes et sexuelles.\n" +
"Former l’ensemble des associations étudiantes, les personnel/les administratif/es et enseignant/e/s chercheurs/euses à la lutte contre les violences sexistes et sexuelles et la prise en charge des victimes.\n" +
"Développer un dispositif de personne de confiance au sein des soirées étudiantes.\n" +
"Diversifier et développer les services de santé universitaire pour répondre aux demandes des étudiant/e/s et accueillir l’ensemble des étudiant/e/s qui en font la demande (reprise des consultations gynéco, embauche de psys...).\n" +
"\n" +
"> Pour des formations accessibles à toutes et à tous :\n" +
"Lutter pour une université gratuite et à moindre coût pour les étudiant/e/s français et internationaux/ales.\n" +
"Développer la valorisation de l’engagement étudiant en promouvant notamment le régime spécifique d’étude et en valorisant l’année de césure.\n" +
"Développer des méthodes d'apprentissage plus interactives, attractives, innovantes et professionnalisantes pour l’ensemble des étudiant/e/s.\n" +
"Généraliser l’approche par compétences pour favoriser la personnalisation du parcours de formation.\n" +
"Créer des UE transversales pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"\n" +
"> Vie étudiante : \n" +
"Créer un guichet d’accès aux droits pour accompagner les étudiant.es dans leurs démarches.\n" +
"Rendre plus accessible la pratique sportive aux étudiant.es en élargissant les plages horaires du SUAPS et en diversifiant les activités proposées.\n" +
"Rendre toujours plus transparente la CVEC et augmenter le financement des projets étudiants.\n" +
"Traduire le site internet de l’université dans différentes langues et le rendre inclusif pour tous/tes.\n" +
"Développer l’accompagnement à la recherche de jobs étudiants.\n" +
"Élargir les horaires d’ouverture de la BU.\n" ,           
            "Programme Amel Boursali", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_amelActionPerformed
//affichage du programe pour ndoumbé bayo
    private void ndouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndouActionPerformed
        JOptionPane.showMessageDialog(null,"Membre de l’association étudiante ZOUZOU\n" +
"> Lutter contre l'oppression de la Droite : \n" +
"Les racistes et réactionnaires ont le vent en poupe, leurs candidats passent tous les jours à la télé. Cela a encouragé des groupes d’extrême-droite de tenter de s’implanter à la fac.\n" +
"La Cocarde a d’abord tenté, mais après avoir été, à de nombreuses reprises, repoussée en dehors de la fac, ils ont finalement abandonné : ils ne se sont même pas présentés à ces élections ! \n " +
"Par contre, nous avons l’UNI... qui se revendique de défendre la “liberté d’étudier”, la réussite, mais dont les principaux dirigeants appellent à voter pour Eric Zemmour, \n "+
"un raciste notoire qui défend la déportation des musulmans ainsi qu’un discours profondément misogyne. Voter UNEF à ces élections, le syndicat qui combat ces idées, \n "+
"c’est la meilleure façon de rejeter leurs idées nauséabondes. C’est aussi soutenir un syndicat qui a obtenu la régularisation de nombreux étudiant/e/s étranger/e/s, \n" +
"l’annulation d’expulsions et qui milite pour l’égalité des droits entre tous les étudiant/e/s.\n" +
"\n" +
"> Une formation ouverte à tous\n" +
"Créer des UE transversales pour intégrer les enjeux de la transition écologique au sein de nos formations.\n" +
"Augmenter les capacités d’accueil en master pour permettre à toutes et tous de bénéficier du droit à la poursuite d’études.\n" +
"Améliorer les conditions de recherche pour les doctorant/e/s : prise en charge des frais complémentaires, veille à la bonne application de la mensualisation des heures de vacations pour les chargé/e/s de TD.\n" +
"Exonérer automatiquement d’au moins 50% les frais d’inscription des doctorant.es (jusqu’à 100% sur critères sociaux).\n" +
"\n" +
"> Vie étudiante : \n" +
"Améliorer la communication de l'université et rendre plus accessible son site internet.\n" +
"Rendre plus accessible la pratique sportive aux étudiant.es en élargissant les plages horaires du SUAPS et en diversifiant les activités proposées.\n" +
"Rendre toujours plus transparente la CVEC et augmenter le financement des projets étudiants.\n" +
"Développer une application pour la vie étudiante et de campus.\n" +
"Développer les parkings à vélo sécurisés sur les campus pour tendre vers des mobilités plus douces pour se déplacer à l’université.\n" +
"Développer le tri sélectif à l’université et la valorisation des déchets organiques.\n",
               "Programme Ndoumbé Bayo",  JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ndouActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deconnexion;
    private javax.swing.JButton Florine;
    private javax.swing.JButton Precedent;
    private javax.swing.JButton ahmed;
    private javax.swing.JButton amel;
    private javax.swing.JButton asli;
    private javax.swing.JButton ayoub;
    private javax.swing.JButton fadoua;
    private javax.swing.JButton ines;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mouna;
    private javax.swing.JButton ndou;
    private javax.swing.JButton nirai;
    // End of variables declaration//GEN-END:variables
}
