/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fenetre;

import javax.swing.JComponent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
//projet L2 MIASHS Amel BOUABDELLAH BOURSALI 400000259 et Ayoub KHAYEF ALLAH 40000476
/**
 *
 * @author boursaliamel
 */
//creation d'une liste de tableau 
public class Vote extends javax.swing.JFrame {
ArrayList<Integer> id = new ArrayList<Integer>();
    int a=13,b=36,c=2,d=18,e=35, f=8, g=1, h=0, i=19 ,j=26  ; 
    
    int flag = 1;
    /**
     * Creates new form Vote
     */
    public Vote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        ahmed = new javax.swing.JButton();
        Deconnexion = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        ndou = new javax.swing.JButton();
        VoteAsli = new javax.swing.JRadioButton();
        VoteFadoua = new javax.swing.JRadioButton();
        VoteFlorine = new javax.swing.JRadioButton();
        VoteNirai = new javax.swing.JRadioButton();
        VoteNdou = new javax.swing.JRadioButton();
        VoteAyoub = new javax.swing.JRadioButton();
        VoteMouna = new javax.swing.JRadioButton();
        VoteInes = new javax.swing.JRadioButton();
        VoteAmel = new javax.swing.JRadioButton();
        VoteAhmed = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        VoirResultat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Id_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/logoufr-SEGMI.jpeg"))); // NOI18N
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(270, 76));
        jLabel2.setMinimumSize(new java.awt.Dimension(270, 76));
        jLabel2.setMixingCutoutShape(null);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Kohinoor Telugu", 1, 30)); // NOI18N
        jButton6.setText("VOTE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1404, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(232, 240, 248));

        jLabel75.setText("EL TEWIL");

        jLabel76.setText("Ahmed");

        jLabel77.setText("L2 MIASHS");

        jLabel78.setText("19 ans");

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_0506 2.JPG"))); // NOI18N

        ahmed.setBackground(new java.awt.Color(255, 255, 255));
        ahmed.setText("Programme");
        ahmed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahmedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ahmed)
                    .addComponent(jLabel76)
                    .addComponent(jLabel75)
                    .addComponent(jLabel78)
                    .addComponent(jLabel77)
                    .addComponent(jLabel80))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel75)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel76)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel77)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel78)
                .addGap(18, 18, 18)
                .addComponent(ahmed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Deconnexion.setBackground(new java.awt.Color(255, 255, 255));
        Deconnexion.setText("DECONNEXION");
        Deconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnexionActionPerformed(evt);
            }
        });

        jPanel18.setBackground(new java.awt.Color(232, 240, 248));

        jLabel84.setText("BAYO");

        jLabel85.setText("Ndoumbé");

        jLabel86.setText("L2 Psychologie");

        jLabel87.setText("19 ans");

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2023.JPG"))); // NOI18N

        ndou.setBackground(new java.awt.Color(255, 255, 255));
        ndou.setText("Programme");
        ndou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ndouActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ndou)
                    .addComponent(jLabel85)
                    .addComponent(jLabel84)
                    .addComponent(jLabel86)
                    .addComponent(jLabel87))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel88)
                .addGap(46, 46, 46))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel88)
                .addGap(30, 30, 30)
                .addComponent(jLabel84)
                .addGap(18, 18, 18)
                .addComponent(jLabel85)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel86)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel87, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ndou)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonGroup2.add(VoteAsli);
        VoteAsli.setText("Asli TAS");

        buttonGroup2.add(VoteFadoua);
        VoteFadoua.setText("Fadoua KASMI");

        buttonGroup2.add(VoteFlorine);
        VoteFlorine.setText("Florine Phillipe");

        buttonGroup2.add(VoteNirai);
        VoteNirai.setText("Nirai RAVIMOHAN");

        buttonGroup2.add(VoteNdou);
        VoteNdou.setText("Ndoumbé BAYO");

        buttonGroup2.add(VoteAyoub);
        VoteAyoub.setText("Ayoub KHAYEF-ALLAH");

        buttonGroup2.add(VoteMouna);
        VoteMouna.setText("Mouna AHMIM");

        buttonGroup2.add(VoteInes);
        VoteInes.setText("Ines TOHNGODO");
        VoteInes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoteInesActionPerformed(evt);
            }
        });

        buttonGroup2.add(VoteAmel);
        VoteAmel.setText("Amel BOURSALI");

        buttonGroup2.add(VoteAhmed);
        VoteAhmed.setText("Ahmed EL TEWIL");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_1999.jpg"))); // NOI18N
        jLabel3.setText("PHOTO");

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2022.JPG"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_1998.jpg"))); // NOI18N
        jLabel20.setText("PHOTO");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_1997.jpg"))); // NOI18N

        jLabel93.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2023.JPG"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/PHOTO-2022-03-05-15-07-59.jpg"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2001.JPG"))); // NOI18N
        jLabel27.setText("PHOTO");

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2002.jpg"))); // NOI18N

        jLabel83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_2012.PNG"))); // NOI18N

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/IMG_0506 2.JPG"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jButton1.setText("VOTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        VoirResultat.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        VoirResultat.setText("RESULTAT");
        VoirResultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoirResultatActionPerformed(evt);
            }
        });

        jLabel6.setText("Pour consulter les résultats actuels: ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fenetre/fleche.jpeg"))); // NOI18N
        jLabel7.setText("Faites glisser à dorite pour voter");
        jLabel7.setToolTipText("");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Deconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1303, 1303, 1303))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel83)
                                        .addComponent(jLabel93, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(VoteAsli)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(VoteNdou)
                                        .addComponent(VoteAmel))
                                    .addGap(71, 71, 71)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel81)
                                            .addGap(18, 18, 18)
                                            .addComponent(VoteFadoua))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel91))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(VoteAyoub)
                                                .addComponent(VoteAhmed))))))
                            .addGap(76, 76, 76)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel62)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(VoteInes)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(9, 9, 9))))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(VoteFlorine)
                                        .addComponent(VoteMouna))
                                    .addGap(116, 116, 116)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(VoteNirai)
                                    .addGap(47, 47, 47))))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VoirResultat)
                                    .addComponent(jLabel6))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel81)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(VoteAsli)))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(VoteFadoua))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(VoteFlorine)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(VoteAyoub))
                                            .addComponent(VoteMouna)))
                                    .addComponent(jLabel27))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(89, 89, 89)
                                        .addComponent(VoteAhmed))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(VoteInes))))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel93)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(83, 83, 83)
                                                .addComponent(VoteNdou))
                                            .addComponent(jLabel14))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel91))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(81, 81, 81)
                                                .addComponent(VoteAmel)))))))
                        .addGap(18, 18, 18)
                        .addComponent(Deconnexion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(VoirResultat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(VoteNirai)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(123, 123, 123)))))
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel4);

        jLabel1.setText("Veuillez à présent choisir le candidat pour qui vous souhaitez voter et appuyer ensuite sur le bouton \"VOTER\"");

        jLabel4.setText("Vous n'avez qu'un vote à attribuer à un seul candidat , et vous n'avez le droit qu'a une tentative c'est à dire qu'une fois avoir appuyer sur le bouton \"VOTER\" aucune action de retractation ou de changement n'est permis. ");

        jLabel5.setText("Pour pouvoir voter merci de rensiegner au préalable votre identifiant : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Connexion().setVisible(true);
        this.setVisible(false);// revenir à la page précédente
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ahmedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahmedActionPerformed

        
    }//GEN-LAST:event_ahmedActionPerformed
//deconnexion
    private void DeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnexionActionPerformed
        // TODO add your handling code here:
        new Electio().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_DeconnexionActionPerformed

    private void ndouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ndouActionPerformed
        
    }//GEN-LAST:event_ndouActionPerformed

    private void VoteInesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoteInesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VoteInesActionPerformed
//Voter
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
if (Id_tf.getText().equals("") || cheak_ckB()==0) { // l'étudiant doit inscrire son numéro étudiat pour voter ainsi nous pouvons vérifier qu'il ne pourra voter qu'une seule foi
            JOptionPane.showMessageDialog(null, "Veuillez saisir votre identifiant pour pouvoir poursuivre et/ou choisir un candidat");
        }   
        else{
        int x = Integer.parseInt(Id_tf.getText());

        cheak_id(x);
        if (flag==1) {
            id.add(x);
//choix du candidat
    
            if (VoteAsli.isSelected()) {
                a++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteFadoua.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteAmel.setSelected(false);
                VoteInes.setSelected(false);
                VoteMouna.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNdou.setSelected(false);
                VoteNirai.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
            }
            else if (VoteFadoua.isSelected()) {
                b++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteAsli.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteAmel.setSelected(false);
                VoteInes.setSelected(false);
                VoteMouna.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNdou.setSelected(false);
                VoteNirai.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
            }
            else if (VoteAyoub.isSelected()) {
                c++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteAsli.setSelected(false);
                VoteFadoua.setSelected(false);
                VoteAmel.setSelected(false);
                VoteInes.setSelected(false);
                VoteMouna.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNdou.setSelected(false);
                VoteNirai.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
            }
            else if (VoteAmel.isSelected()) {
                d++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteAsli.setSelected(false);
                VoteFadoua.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteInes.setSelected(false);
                VoteMouna.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNdou.setSelected(false);
                VoteNirai.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
            }
            else if (VoteInes.isSelected()) {
                e++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteAsli.setSelected(false);
                VoteFadoua.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteAmel.setSelected(false);
                VoteMouna.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNdou.setSelected(false);
                VoteNirai.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
            
        }else if (VoteMouna.isSelected()) {
                f++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteAsli.setSelected(false);
                VoteFadoua.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteAmel.setSelected(false);
                VoteInes.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNdou.setSelected(false);
                VoteNirai.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
            
            
        
      }else if (VoteAhmed.isSelected()) {
                g++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteAsli.setSelected(false);
                VoteFadoua.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteAmel.setSelected(false);
                VoteInes.setSelected(false);
                VoteMouna.setSelected(false);
                VoteNdou.setSelected(false);
                VoteNirai.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
            
    }
            else if (VoteNdou.isSelected()) {
                h++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteAsli.setSelected(false);
                VoteFadoua.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteAmel.setSelected(false);
                VoteInes.setSelected(false);
                VoteMouna.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNirai.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
            }
            else if (VoteNirai.isSelected()) {
                i++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
                VoteAsli.setSelected(false);
                VoteFadoua.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteAmel.setSelected(false);
                VoteInes.setSelected(false);
                VoteMouna.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNdou.setSelected(false);
                VoteFlorine.setSelected(false);
                buttonGroup2.clearSelection();
                
            }else if (VoteFlorine.isSelected()) {
                j++;
                JOptionPane.showMessageDialog(null, " Votre vote a été pris en compte avec succès");
                
               VoteAsli.setSelected(false);
                VoteFadoua.setSelected(false);
                VoteAyoub.setSelected(false);
                VoteAmel.setSelected(false);
                VoteInes.setSelected(false);
                VoteMouna.setSelected(false);
                VoteAhmed.setSelected(false);
                VoteNdou.setSelected(false);
                VoteNirai.setSelected(false);
                buttonGroup2.clearSelection();
            
            }
        }
        else{
      JOptionPane.showMessageDialog(null, "Vous n'avez le droit de voter qu'une seule fois");
        }  
    }  
    }//GEN-LAST:event_jButton1ActionPerformed
//permet de se rendre à la page résultat
    private void VoirResultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoirResultatActionPerformed
        Resultats frame = new Resultats(a,b,c,d,e,f,g,h,i,j);
            frame.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_VoirResultatActionPerformed

    // permet de verifier que id est bien inscrit sur le champs "id" 
    private void cheak_id(int c){
        
        if (id.size()== 0) {
           flag = 1;
        }
        else{
            
            for (int i : id) {
                if (c==i) {
                    flag = 0;
                }
                else{
                   flag = 1;
                }
            }
        }
}

    //permet de verifier qu'un candidat est selectionné 
  private int cheak_ckB(){
    
        boolean a1 = VoteAsli.isSelected();
        boolean b1 = VoteFadoua.isSelected();
        boolean c1 = VoteAyoub.isSelected();
        boolean d1 = VoteAmel.isSelected();
        boolean e1 = VoteInes.isSelected();
        boolean f1 = VoteMouna.isSelected();
        boolean g1 = VoteAhmed.isSelected();
        boolean h1 = VoteNdou.isSelected();
        boolean i1 = VoteNirai.isSelected();
        boolean j1 = VoteFlorine.isSelected();
        
        if (a1==false&&b1==false&&c1==false&&d1==false&&e1==false&&f1==false&&g1==false&&h1==false&&i1==false&&j1==false) {
                return 0;
            }
            else{
               
               return 1;  
            }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
public void run() {
                new Vote().setVisible(true);
            }
        });

    
}
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deconnexion;
    private javax.swing.JTextField Id_tf;
    private javax.swing.JButton VoirResultat;
    private javax.swing.JRadioButton VoteAhmed;
    private javax.swing.JRadioButton VoteAmel;
    private javax.swing.JRadioButton VoteAsli;
    private javax.swing.JRadioButton VoteAyoub;
    private javax.swing.JRadioButton VoteFadoua;
    private javax.swing.JRadioButton VoteFlorine;
    private javax.swing.JRadioButton VoteInes;
    private javax.swing.JRadioButton VoteMouna;
    private javax.swing.JRadioButton VoteNdou;
    private javax.swing.JRadioButton VoteNirai;
    private javax.swing.JButton ahmed;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ndou;
    // End of variables declaration//GEN-END:variables

    private void doubleClicked(JComponent jComponent) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}

